name: job_time
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  asuka: ^2.0.1+1
  bloc: ^8.1.0
  equatable: ^2.0.5
  firebase_auth: ^3.9.0
  firebase_core: ^1.22.0
  fl_chart: ^0.55.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_modular: ^5.0.3
  google_sign_in: ^5.4.1
  isar: ^3.0.0
  isar_flutter_libs: ^3.0.0
  modular_bloc_bind: ^1.0.1
  path_provider: ^2.0.11
  url_strategy: ^0.2.0
  validatorless: ^1.2.1

dev_dependencies:
  build_runner: ^2.2.1
  dart_code_metrics: ^4.18.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: JobTimerIcons
      fonts:
        - asset: assets/fonts/JobTimerIcons.ttf
