name: job_time
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.0.5

dependencies:
  asuka: ^2.1.0
  equatable: ^2.0.5
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_modular: ^5.0.3
  google_sign_in: ^6.1.4
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  modular_bloc_bind: ^1.0.1
  path_provider: ^2.0.15
  url_strategy: ^0.2.0
  validatorless: ^1.2.3

dev_dependencies:
  build_runner: ^2.4.5
  dart_code_metrics: ^5.7.5
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: JobTimerIcons
      fonts:
        - asset: assets/fonts/JobTimerIcons.ttf
