name: job_time
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  asuka: ^2.0.0+1
  bloc: ^8.0.3
  cupertino_icons: ^1.0.5
  equatable: ^2.0.3
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  fl_chart: ^0.55.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_modular: ^5.0.3
  google_sign_in: ^5.3.3
  google_sign_in_web: ^0.10.2
  isar: ^3.0.0-dev.5
  isar_flutter_libs: ^3.0.0-dev.5
  modular_bloc_bind: ^1.0.1
  path_provider: ^2.0.11
  url_strategy: ^0.2.0
  validatorless: ^1.2.1

dev_dependencies:
  build_runner: ^2.1.11
  dart_code_metrics: ^4.16.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.0-dev.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: JobTimerIcons
      fonts:
        - asset: assets/fonts/JobTimerIcons.ttf
