// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBasp7QpsUNP6vZxqpCNe0T43t6kdylLwI',
    appId: '1:618675307153:web:fac34e0fc6790527d03530',
    messagingSenderId: '618675307153',
    projectId: 'dw-7-job-timer-roveri',
    authDomain: 'dw-7-job-timer-roveri.firebaseapp.com',
    storageBucket: 'dw-7-job-timer-roveri.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFMCLv10l5Q6JTOKq8V_jXC5KInFvYI8A',
    appId: '1:618675307153:android:91c803ea9a485fbad03530',
    messagingSenderId: '618675307153',
    projectId: 'dw-7-job-timer-roveri',
    storageBucket: 'dw-7-job-timer-roveri.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaXSC83K1ulzaypeAphOMymnSCyrK0skM',
    appId: '1:618675307153:ios:96d4c897ec06821dd03530',
    messagingSenderId: '618675307153',
    projectId: 'dw-7-job-timer-roveri',
    storageBucket: 'dw-7-job-timer-roveri.appspot.com',
    androidClientId: '618675307153-dtn2rckdgbi2h1mikfegkrr6t7ue7ljh.apps.googleusercontent.com',
    iosClientId: '618675307153-hbgpgtvsg3ajoj4h8im0fq5rhkmg65ej.apps.googleusercontent.com',
    iosBundleId: 'br.com.roveri.jobTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaXSC83K1ulzaypeAphOMymnSCyrK0skM',
    appId: '1:618675307153:ios:96d4c897ec06821dd03530',
    messagingSenderId: '618675307153',
    projectId: 'dw-7-job-timer-roveri',
    storageBucket: 'dw-7-job-timer-roveri.appspot.com',
    androidClientId: '618675307153-dtn2rckdgbi2h1mikfegkrr6t7ue7ljh.apps.googleusercontent.com',
    iosClientId: '618675307153-hbgpgtvsg3ajoj4h8im0fq5rhkmg65ej.apps.googleusercontent.com',
    iosBundleId: 'br.com.roveri.jobTime',
  );
}
